package Designs;

import Connects.myCon;
import java.awt.print.PageFormat;
import java.awt.print.Paper;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

public class ReceiptForm extends java.awt.Dialog {

    myCon mets = new myCon();
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;

    public ReceiptForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        conn = myCon.ConnecrDb();
        setIconImage(mets.myImage("/Icons/globe.png"));
        btn_Print.setVisible(false);
    }

    public void invoice_job() {
        try {
            int rows = StudentForm.studentPerformanceTable.getRowCount();
            PrinterJob printerJob = PrinterJob.getPrinterJob();
            PageFormat pageFormat = printerJob.defaultPage();
            Paper paper = new Paper();
            paper.setSize(600, (double) (paper.getHeight() - rows * 1));
            paper.setImageableArea(paper.getWidth() + rows * 5, 20, paper.getWidth() - rows * 2, paper.getHeight() - rows * 2);
            pageFormat.setPaper(paper);
            pageFormat.setOrientation(PageFormat.PORTRAIT);
            printerJob.setPrintable(pane.getPrintable(null, null), pageFormat);
            printerJob.print();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void printReport() {
        try {
            int rows = 1200;
            PrinterJob printerJob = PrinterJob.getPrinterJob();
            PageFormat pageFormat = printerJob.defaultPage();
            Paper paper = new Paper();
            paper.setSize(600, (double) (paper.getHeight() - rows * 50));
            paper.setImageableArea(paper.getWidth() + rows * 5, 120, paper.getWidth() - rows * 2, paper.getHeight() - rows * 5);
            pageFormat.setPaper(paper);
            pageFormat.setOrientation(PageFormat.PORTRAIT);
            printerJob.setPrintable(pane.getPrintable(null, null), pageFormat);
            printerJob.print();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
       public void Print() {
        try {
            Boolean complete = pane.print();
            if (complete) {
                JOptionPane.showMessageDialog(null, "Done Printing....");
            } else {
                JOptionPane.showMessageDialog(null, "Printing.....");
            }
        } catch (PrinterException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    public void setPageMe() {
        JScrollPane editorScrollPane = new JScrollPane(pane);
        editorScrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
        File file = new File("C://newhtml.html");

        try {
            pane.setPage(file.toURI().toURL());
        } catch (IOException ex) {
            Logger.getLogger(ReceiptForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        pane.setEditable(true);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pane = new javax.swing.JTextPane();
        btn_Print = new javax.swing.JButton();
        print_me = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(577, 670));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setPreferredSize(new java.awt.Dimension(534, 650));

        pane.setEditable(false);
        pane.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));
        pane.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jScrollPane1.setViewportView(pane);

        btn_Print.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Print.setForeground(new java.awt.Color(51, 102, 0));
        btn_Print.setText("Print");
        btn_Print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PrintActionPerformed(evt);
            }
        });

        print_me.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        print_me.setForeground(new java.awt.Color(102, 0, 0));
        print_me.setText("Print");
        print_me.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                print_meActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 434, Short.MAX_VALUE)
                .addComponent(print_me)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Print)
                .addContainerGap())
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(print_me, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Print, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void btn_PrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PrintActionPerformed
        invoice_job();
    }//GEN-LAST:event_btn_PrintActionPerformed

    private void print_meActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_print_meActionPerformed
        printReport();
    }//GEN-LAST:event_print_meActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
        UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ReceiptForm dialog = new ReceiptForm(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btn_Print;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextPane pane;
    public static javax.swing.JButton print_me;
    // End of variables declaration//GEN-END:variables
}
